/*MOST BORROWED ITEM*/
SELECT SUPPLY_TYPE,SUM(CASE WHEN SUPPLY_STATUS = 'Available' THEN 1 END) 
FROM SCHOOL_SUPPLIES GROUP BY SUPPLY_TYPE ORDER BY SUM(CASE WHEN SUPPLY_STATUS = 'Available' THEN 1 END) DESC;

/*PERCENT OF STUDENT IN COURSE*/
SELECT COURSE_CODE,COUNT(e.SECTION_CODE),s.MAX_STUDENT + s.MAX_STUDENT, (COUNT(e.SECTION_CODE)/(s.MAX_STUDENT + s.MAX_STUDENT))*100
FROM (ENROLLED_SECTION e JOIN SECTION s ON e.SECTION_CODE = s.SECTION_CODE) GROUP BY COURSE_CODE ORDER BY COUNT(e.SECTION_CODE) DESC;

/*Percentage of students taking the same course twice or more*/
SELECT COUNT(e.USER_ID), e.USER_ID, s.COURSE_CODE
    FROM SECTION s JOIN ENROLLED_SECTION es ON s.SECTION_CODE = es.SECTION_CODE JOIN ENROLLMENT e ON es.ENROLLMENT_ID = e.ENROLLMENT_ID
    GROUP BY s.COURSE_CODE, e.USER_ID;

/*Calculate GPA*/
SELECT ENROLLMENT_ID,ACADEMIC_YEAR,SEMESTER,GPA FROM ENROLLMENT

/*Average grade of courses*/
SELECT ACADEMIC_YEAR,SEMESTER,COURSE_CODE,SUM(grade)/COUNT(grade) 
    FROM ((ENROLLED_SECTION es JOIN SECTION s ON es.SECTION_CODE = s.SECTION_CODE)
            JOIN ENROLLMENT e ON e.ENROLLMENT_ID = es.ENROLLMENT_ID) GROUP BY COURSE_CODE