/* INSERT DATA IN COURSE TABLE */
INSERT INTO course (COURSE_CODE, COURSE_TITLE, PRICE_RATE_ID) VALUES ('CPE213', 'Data Models', 'PR36000');
INSERT INTO course (COURSE_CODE, COURSE_TITLE, PRICE_RATE_ID) VALUES ('CPE231', 'Database Systems', 'PR36000');
INSERT INTO course (COURSE_CODE, COURSE_TITLE, PRICE_RATE_ID) VALUES ('CPE224', 'Computer Achitectures', 'PR36000');
INSERT INTO course (COURSE_CODE, COURSE_TITLE, PRICE_RATE_ID) VALUES ('GEN111', 'Man and Ethics of Living', 'PR12000');

/* CREATE TABLE TO CHECK INSERT VALUES */
CREATE TABLE tmp SELECT COURSE_CODE, COURSE_TITLE, Price_Rate_ID
   	FROM course
   	GROUP BY COURSE_CODE, COURSE_TITLE;

/* INSERT VALUES INTO tmp*/
INSERT INTO tmp VALUES('CPE213', 'Data Models', 'PR36000'); #duplicate 
INSERT INTO tmp VALUES('MTH001', 'math1', 'PR36000'); #correct values
INSERT INTO tmp VALUES('MTH002', 'math2', 'PR10000'); #wrong price

/* INSERT FROM tmp TO COURSE */
INSERT IGNORE INTO course (COURSE_CODE, COURSE_TITLE, Price_Rate_ID)
	select  COURSE_CODE, COURSE_TITLE, Price_Rate_ID from tmp
	WHERE NOT EXISTS (SELECT * FROM course
	where Price_Rate_ID='PR12000' and Price_Rate_ID='PR36000');

/* DELETE tmp TABLE*/
DROP TABLE tmp;

/* DELETE values from COURSE TABLE*/
DELETE FROM course
WHERE COURSE_CODE = ‘math1';