/* Name Database: c5_studentregistration*/
CREATE TABLE USER_T (
    USER_ID         VARCHAR(50)     NOT NULL,
    PASSWORD        VARCHAR(50)     NOT NULL,
    NATIONAL_ID     VARCHAR(50)     NULL,
    FIRST_NAME      VARCHAR(50)     NOT NULL,
    LAST_NAME       VARCHAR(50)     NOT NULL,
    DEPARTMENT      VARCHAR(50)     NOT NULL,
    TOTAL_CREDIT    INT(3)          NOT NULL,
    GPAX            DOUBLE(3, 2)    NULL,
    YEAR            INT(2)          NOT NULL,
    ROLE            VARCHAR(50)     NOT NULL,
    PRIMARY KEY (USER_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE SCHOOL_SUPPLIES (
    SUPPLY_ID           VARCHAR(50) NOT NULL,
    SUPPLY_TYPE         VARCHAR(50) NOT NULL,
    MODELS              VARCHAR(50) NOT NULL,
    SUPPLY_STATUS       VARCHAR(50) NOT NULL,
    END_OF_DUTY_DATE    DATE        NOT NULL,
    PRIMARY KEY (SUPPLY_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE BORROW_LIST (
    USER_ID         VARCHAR(50) NOT NULL,
    SUPPLY_ID       VARCHAR(50) NOT NULL,
    SEMESTER        INT(1)      NOT NULL,
    ACADEMIC_YEAR   INT(4)      NOT NULL,
    BORROW_STATUS   VARCHAR(50) NOT NULL,
    PRIMARY KEY (USER_ID, SUPPLY_ID, SEMESTER, ACADEMIC_YEAR),
    FOREIGN KEY (USER_ID) REFERENCES USER_T(USER_ID),
    FOREIGN KEY (SUPPLY_ID) REFERENCES SCHOOL_SUPPLIES(SUPPLY_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE ENROLLMENT (
    ENROLLMENT_ID   VARCHAR(50)     NOT NULL,
    USER_ID         VARCHAR(50)     NOT NULL,
    TOTAL_PRICE     INT(6)          NOT NULL,
    TOTAL_CREDIT    INT(2)          NOT NULL,
    PAYMENT_STATUS  BOOLEAN         NOT NULL,
    GPA             DOUBLE(3, 2)    NULL,
    SEMESTER        INT(1)          NOT NULL,
    ACADEMIC_YEAR   INT(4)          NOT NULL,
    PRIMARY KEY (ENROLLMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER_T(USER_ID) 
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE BILL_PAYMENT (
    PAYMENT_ID          VARCHAR(50) NOT NULL,
    ENROLLMENT_ID       VARCHAR(50) NOT NULL,
    TRANSITION_NUMBER   VARCHAR(50) NULL,
    DUE_PHASE           INT(1)      NOT NULL,
    PRICE               INT(6)      NOT NULL,
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENT(ENROLLMENT_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE PRICE_COURSE (
    Price_Rate_ID   VARCHAR(50) NOT NULL,
    CREDIT          INT(1)      NOT NULL,
    PRICE           INT(5)      NOT NULL,
    PRIMARY KEY (Price_Rate_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE COURSE (
    COURSE_CODE     VARCHAR(50) NOT NULL,
    COURSE_TITLE    VARCHAR(128) NOT NULL,
    Price_Rate_ID   VARCHAR(50) NOT NULL,
    PRIMARY KEY (COURSE_CODE),
    FOREIGN KEY (Price_Rate_ID) REFERENCES PRICE_COURSE(Price_Rate_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE SECTION (
    SECTION_CODE    VARCHAR(50) NOT NULL,
    COURSE_CODE     VARCHAR(50) NOT NULL,
    MAX_STUDENT     INT(3)      NOT NULL,
    PRIMARY KEY (SECTION_CODE),
    FOREIGN KEY (COURSE_CODE) REFERENCES COURSE(COURSE_CODE)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE ENROLLED_SECTION (
    ENROLLMENT_ID   VARCHAR(50)     NOT NULL,
    SECTION_CODE    VARCHAR(50)     NOT NULL,
    GRADE           DOUBLE(3, 2)    NULL,
    PRIMARY KEY (ENROLLMENT_ID, SECTION_CODE),
    FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENT(ENROLLMENT_ID),
    FOREIGN KEY (SECTION_CODE) REFERENCES SECTION(SECTION_CODE)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE CORE_COURSE (
    COURSE_CODE     VARCHAR(50) NOT NULL,
    DEPARTMENT      VARCHAR(50) NOT NULL,
    CORE_COURSE     BOOLEAN     NOT NULL,
    SEMESTER        INT(1)      NOT NULL,
    YEAR            INT(2)      NOT NULL,
    PRIMARY KEY (COURSE_CODE, DEPARTMENT),
    FOREIGN KEY (COURSE_CODE) REFERENCES COURSE(COURSE_CODE)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE TEACHER (
    TEACHER_ID      VARCHAR(50) NOT NULL,
    FIRST_NAME      VARCHAR(50) NOT NULL,
    LAST_NAME       VARCHAR(50) NOT NULL,
    DEPARTMENT      VARCHAR(50) NOT NULL,
    PRIMARY KEY (TEACHER_ID)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE SECTION_TEACHER (
    TEACHER_ID      VARCHAR(50) NOT NULL,
    SECTION_CODE    VARCHAR(50) NOT NULL,
    PRIMARY KEY (TEACHER_ID, SECTION_CODE),
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TEACHER_ID),
    FOREIGN KEY (SECTION_CODE) REFERENCES SECTION(SECTION_CODE)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE 1CURRENT_TIME (
    ACADEMIC_YEAR   INT(4) NOT NULL,
    SEMESTER        INT(1) NOT NULL,
    PHASE           INT(1) NOT NULL
)ENGINE = InnoDB DEFAULT CHARSET = utf8;